# To configure the environment locally to test the website, check out
# https://help.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll

title: Java SDK for CloudEvents
remote_theme: pmarsceill/just-the-docs
plugins:
    - jemoji

search_enabled: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/cloudevents/sdk-java"
gh_edit_branch: "master"
gh_edit_source: docs
gh_edit_view_mode: "tree"

aux_links:
    "GitHub Repository":
        - "https://github.com/cloudevents/sdk-java"
    "CloudEvents home":
        - "https://cloudevents.io/"
